COURSES = [
    {
        "id": 1,
        "mountain": "관악산",
        "name": "서울대입구 둘레길 코스",
        "region": "서울 관악구",
        "difficulty": "easy",
        "distance_km": 3.4,
        "duration_min": 95,
        "elevation_gain_m": 180,
        "lat": 37.445,
        "lng": 126.951,
        "crowding": 0.42,
        "highlights": ["완만한 초입", "대중교통 접근 우수", "짧은 회복형 코스"],
    },
    {
        "id": 2,
        "mountain": "북한산",
        "name": "우이령 숲길 코스",
        "region": "서울 강북구",
        "difficulty": "easy",
        "distance_km": 4.6,
        "duration_min": 130,
        "elevation_gain_m": 220,
        "lat": 37.662,
        "lng": 127.012,
        "crowding": 0.37,
        "highlights": ["숲길 중심", "동반 산행 적합", "일몰 전 하산 여유"],
    },
    {
        "id": 3,
        "mountain": "청계산",
        "name": "원터골-매봉 코스",
        "region": "서울 서초구",
        "difficulty": "medium",
        "distance_km": 5.2,
        "duration_min": 165,
        "elevation_gain_m": 430,
        "lat": 37.427,
        "lng": 127.055,
        "crowding": 0.58,
        "highlights": ["운동 강도 확보", "정상 조망", "초중급자 인기"],
    },
    {
        "id": 4,
        "mountain": "아차산",
        "name": "고구려정 전망 코스",
        "region": "서울 광진구",
        "difficulty": "easy",
        "distance_km": 2.8,
        "duration_min": 75,
        "elevation_gain_m": 155,
        "lat": 37.573,
        "lng": 127.103,
        "crowding": 0.64,
        "highlights": ["짧은 전망 코스", "초보자 적합", "야외 산책 느낌"],
    },
    {
        "id": 5,
        "mountain": "수락산",
        "name": "벽운계곡 왕복 코스",
        "region": "서울 노원구",
        "difficulty": "hard",
        "distance_km": 6.8,
        "duration_min": 230,
        "elevation_gain_m": 620,
        "lat": 37.699,
        "lng": 127.083,
        "crowding": 0.33,
        "highlights": ["계곡 경관", "상급자 운동 코스", "혼잡도 낮음"],
    },
]

MOCK_WEATHER = {
    "temperature_c": 18,
    "rainfall_mm": 0,
    "wind_speed_ms": 2.7,
    "humidity_pct": 54,
    "sunset": "19:28",
    "wildfire_risk": "low",
}
