# 산림청 API 자동 수집 — collect_mountains2.py

MOUNTAINS = [
    {
        "id": "m-설악산",
        "name": "설악산",
        "region": "강원 속초시",
        "lat": 38.119444,
        "lng": 128.465556,
        "elevation_m": 1708,
        "difficulty": "hard",
        "walk_time_min": 360,
        "walk_time_max": 720,
        "trail_count": 13,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view", "workout"],
        "crowding": 0.68,
        "national_park": True,
        "highlights": ["국립공원", "설경 명소"],
        "description": "한마디로 한국의 알프스다. 흔히 금강산에 비유하지만 높이도 72미터나 낮고 동서로 긴 능선이 없어 산역은 훨씬 좁다.",
    },
    {
        "id": "m-지리산",
        "name": "지리산",
        "region": "경남 산청군",
        "lat": 35.336944,
        "lng": 127.730556,
        "elevation_m": 1915,
        "difficulty": "hard",
        "walk_time_min": 360,
        "walk_time_max": 720,
        "trail_count": 34,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view", "workout"],
        "crowding": 0.55,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "지리산은 크다. 높고도 넓고 그리고 깊다. 3도 여섯 고을―함양, 산청, 하동, 구례, 남원, 운봉[현]에 그림자 드리운 거대한 산국(山國)이다.",
    },
    {
        "id": "m-한라산",
        "name": "한라산",
        "region": "제주 제주시",
        "lat": 33.361667,
        "lng": 126.529167,
        "elevation_m": 1947,
        "difficulty": "hard",
        "walk_time_min": 360,
        "walk_time_max": 720,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view", "workout"],
        "crowding": 0.7,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "한반도 남쪽의 최고봉, 해발 1950m의 한라산은 제주도 사람들의 숨결과 역사를 그대로 안고 있는 산이다.",
    },
    {
        "id": "m-북한산",
        "name": "북한산",
        "region": "서울 강북구",
        "lat": 37.658611,
        "lng": 126.977389,
        "elevation_m": 836,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 59,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.82,
        "national_park": True,
        "highlights": ["국립공원", "설경 명소", "암릉 경관"],
        "description": "북한산은 성채다. 최고봉 백운대를 비롯하여 인수봉, 노적봉, 의상봉, 보현봉 등 걸출한 암봉들이 험준한 산세를 이루고 여기 의지하여 사람들이 진짜 성을 쌓았다.",
    },
    {
        "id": "m-오대산",
        "name": "오대산",
        "region": "강원 평창군",
        "lat": 37.794444,
        "lng": 128.543611,
        "elevation_m": 1565,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 27,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "healing", "workout"],
        "crowding": 0.48,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "다섯 개의 봉우리를 가진 산이란 뜻의 오대산은 동서 20km, 남북 33km, 660㎢의 광대한 면적을 자랑한다.",
    },
    {
        "id": "m-소백산",
        "name": "소백산",
        "region": "충북 단양군",
        "lat": 36.957778,
        "lng": 128.484444,
        "elevation_m": 1440,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 11,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "소백산(1439.7m)은 백두대간이 거느린 명산 중 하나다.",
    },
    {
        "id": "m-태백산",
        "name": "태백산",
        "region": "강원 태백시",
        "lat": 37.095833,
        "lng": 128.916667,
        "elevation_m": 1567,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 10,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "신라 임금이 둘씩이나 순행을 갔던 성산(聖山)이다. 그때는 물론 봉화 태백산이었는 바 기실은 그쪽이 태백산의 정면이다.",
    },
    {
        "id": "m-치악산",
        "name": "치악산",
        "region": "강원 원주시",
        "lat": 37.365,
        "lng": 128.055556,
        "elevation_m": 1282,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 4,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.45,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "명산은 가까이 가보면 안다. 영동고속국도 원주를 지날 무렵 뭇 산을 제압하는 훤칠한 산이 보인다면 물어볼 것도 없이 치악산인 것이다. 들고을 원주(原州)에서 보면 그건 거대한 장벽이다.",
    },
    {
        "id": "m-월악산",
        "name": "월악산",
        "region": "충북 제천시",
        "lat": 36.889444,
        "lng": 128.105556,
        "elevation_m": 1095,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 10,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.42,
        "national_park": True,
        "highlights": ["국립공원", "설경 명소", "사찰 탐방"],
        "description": "월악산(1095.3m)은 설악산의 현란한 아름다움과 지리산의 장엄함을 조금씩 가져다 놓은 듯한 산세를 지녔다. 깎아지른 절벽이 가슴 조이게 하지만 부드러운 능선의 푸근함도 함께 주는 산이다.",
    },
    {
        "id": "m-속리산",
        "name": "속리산",
        "region": "충북 보은군",
        "lat": 36.543056,
        "lng": 127.870833,
        "elevation_m": 1058,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 12,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.52,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "속리산은 1970년 국립공원으로 지정된 대한팔경 중 하나다.",
    },
    {
        "id": "m-계룡산",
        "name": "계룡산",
        "region": "충남 공주시",
        "lat": 36.342778,
        "lng": 127.205556,
        "elevation_m": 847,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 8,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.55,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "계룡산은 수려한 산세와 승지 신도안, 여러 고찰들을 품은 충남 제일의 명산이다. 이미 신라시대 5악의 하나였고 조선시대에는 묘향산, 지리산과 함께 산신제를 올리던 영산이었다.",
    },
    {
        "id": "m-덕유산",
        "name": "덕유산",
        "region": "전북 무주군",
        "lat": 35.859722,
        "lng": 127.746389,
        "elevation_m": 1507,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 3,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.45,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "전북 무주·경남 거창에 걸친 국립공원. 주봉 향적봉(1614m)에서 남덕유산으로 이어지는 60리 능선이 장관이다. 겨울 설경과 야생화 군락으로 사계절 모두 아름답다.",
    },
    {
        "id": "m-가야산",
        "name": "가야산",
        "region": "경남 합천군",
        "lat": 35.823611,
        "lng": 128.120833,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 2,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.55,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "경남 합천·경북 성주 경계의 국립공원(1430m). 우두봉의 거대한 암벽이 한눈에 시선을 압도한다. 팔만대장경을 소장한 해인사를 품고 있어 역사·자연이 함께 살아 숨 쉬는 명산이다.",
    },
    {
        "id": "m-내장산",
        "name": "내장산",
        "region": "전북 정읍시",
        "lat": 35.478333,
        "lng": 126.8875,
        "elevation_m": 764,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 5,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.58,
        "national_park": True,
        "highlights": ["국립공원", "단풍 명소"],
        "description": "우리나라에서 \"\"단풍\"\" 하면 제일 먼저 떠오르는 산이 바로 내장산이다. 동구부터 내장사까지 3킬로미터 남짓 되는 길가가 온통 단풍나무밭이다.",
    },
    {
        "id": "m-무등산",
        "name": "무등산",
        "region": "광주 동구",
        "lat": 35.134167,
        "lng": 126.988889,
        "elevation_m": 1187,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 14,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.58,
        "national_park": True,
        "highlights": ["국립공원", "암릉 경관", "계곡 트레킹"],
        "description": "무등산은 산줄기와 골짜기가 뚜렷하지 않고 마치 커다란 둔덕과 같은 산세를 지닌 홑산이다. 가장 큰 특징은 너덜지대로, 천왕봉 남쪽의 지공너덜과 증심사 동쪽의 덕산너덜은 장관을 자랑한다.",
    },
    {
        "id": "m-주왕산",
        "name": "주왕산",
        "region": "경북 청송군",
        "lat": 36.389444,
        "lng": 129.163611,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 5,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.48,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "경북 청송의 국립공원(720m). 기암절벽과 폭포가 어우러진 주방천 협곡이 이 산의 백미다. 수직으로 치솟은 바위 기둥들 사이를 걷는 계곡 산행이 인상적이다.",
    },
    {
        "id": "m-월출산",
        "name": "월출산",
        "region": "전남 영암군",
        "lat": 34.765,
        "lng": 126.704444,
        "elevation_m": 811,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 3,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.42,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "프랑스의 세계문화유산 몽쌩미쉘(Mont Saint-Michel) 같은 산이다. 정상 천황봉만 떼어 보면 피라밋 같기도 하다. 천황사쪽 평균경사 37도.",
    },
    {
        "id": "m-팔공산",
        "name": "팔공산",
        "region": "대구 동구",
        "lat": 35.992,
        "lng": 128.686,
        "elevation_m": 1192,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 7,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.6,
        "national_park": True,
        "highlights": ["국립공원", "암릉 경관", "사찰 탐방"],
        "description": "신라의 중악(中岳) 팔공산은 대구산악인의 모산이며 약사신앙의 1번지다.",
    },
    {
        "id": "m-도봉산",
        "name": "도봉산",
        "region": "서울 도봉구",
        "lat": 37.698056,
        "lng": 127.015278,
        "elevation_m": 740,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.78,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "서울 도봉·경기 양주 경계의 암릉 명산(740m). 자운봉·만장봉·선인봉 등 화강암 암봉이 빼곡히 솟아 서울 시민들이 가장 사랑하는 암릉 산행지다. 북한산과 능선으로 이어진다.",
    },
    {
        "id": "m-관악산",
        "name": "관악산",
        "region": "서울 관악구",
        "lat": 37.442424,
        "lng": 126.963344,
        "elevation_m": 632,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.75,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "옛 과천현의 진산이지만 정면은 서울쪽이다. 거기다 산세가 화성(火星)의 극치를 이뤄 불꽃 너울이 상봉으로 수렴, 하늘을 태우는 듯하다.",
    },
    {
        "id": "m-두타산",
        "name": "두타산",
        "region": "강원 동해시",
        "lat": 37.399444,
        "lng": 129.071111,
        "elevation_m": 1357,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view", "workout"],
        "crowding": 0.35,
        "national_park": False,
        "highlights": ["암릉 경관", "계곡 트레킹"],
        "description": "계곡 이름을 무릉계(武陵溪)라고 했다. 얼마나 대단한 경치면 감히 “무릉도원은 바로 여기”라고 내세웠다. 두타산과 청옥산, 고적대, 갈미봉, 1243봉으로 둘러싸인 반석계곡이다.",
    },
    {
        "id": "m-함백산",
        "name": "함백산",
        "region": "강원 태백시",
        "lat": 37.148889,
        "lng": 128.896111,
        "elevation_m": 1573,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 2,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.32,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "강원 정선·태백 경계의 백두대간 고봉(1573m). 정상까지 차로 올라갈 수 있는 접근성 덕에 야간 별 관측지로도 인기 높다. 고산 야생화와 눈꽃이 볼 만하다.",
    },
    {
        "id": "m-민주지산",
        "name": "민주지산",
        "region": "충북 영동군",
        "lat": 36.044444,
        "lng": 127.86,
        "elevation_m": 1242,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["계곡 트레킹"],
        "description": "민주지산(1241.7m)은 충북, 경북, 전북 등 3도에 걸쳐 있다.",
    },
    {
        "id": "m-황매산",
        "name": "황매산",
        "region": "경남 합천군",
        "lat": 35.519,
        "lng": 127.976,
        "elevation_m": 1113,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.35,
        "national_park": False,
        "highlights": ["철쭉 명소", "억새 군락"],
        "description": "합천호반을 지나다 보면 남쪽 하늘금에 굉장한 산 하나가 솟아있다. 이 근처에도 저런 높은 산이 있었나 싶을 만큼 준걸한 암봉이 호숫물에 어린다. 지도를 펴보면… 황매산이다.",
    },
    {
        "id": "m-금오산",
        "name": "금오산",
        "region": "경북 구미시",
        "lat": 36.142,
        "lng": 128.318,
        "elevation_m": 634,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경북 구미의 진산(976m). 도선굴·마애보살좌상·약사암 등 불교 문화재가 곳곳에 남아 있다. 금오산댐에서 정상까지 능선이 뚜렷하고 조망이 시원하다.",
    },
    {
        "id": "m-비슬산",
        "name": "비슬산",
        "region": "대구 달성군",
        "lat": 35.734444,
        "lng": 128.491667,
        "elevation_m": 1083,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "대구를 분지로 만드는 두 산은 팔공산과 비슬산이다. 화강암질의 팔공산이 산세가 웅장하여 아버지 산이라면 안산암질의 비슬산은 온화하고 부드러워 어머니 산이라 할 만하다.",
    },
    {
        "id": "m-운문산",
        "name": "운문산",
        "region": "경북 청도군",
        "lat": 35.613333,
        "lng": 128.988889,
        "elevation_m": 1195,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["암릉 경관", "정상 전망 우수"],
        "description": "거울에 비친 下자형 산줄기 영남알프스의 윗금 서쪽끝을 이루는 산이다.",
    },
    {
        "id": "m-재약산",
        "name": "재약산",
        "region": "경남 밀양시",
        "lat": 35.484167,
        "lng": 128.9975,
        "elevation_m": 1119,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["사찰 탐방"],
        "description": "왼손으로 쓴 下자 형국 영남알프스의 점에 해당하는 산이다. 그만큼 깊이 숨어있는 산중 속의 산으로 빙 둘러 타원형 능선이 길지를 품고있다. 표충사.",
    },
    {
        "id": "m-신불산",
        "name": "신불산",
        "region": "경남 울주군",
        "lat": 35.444167,
        "lng": 129.0725,
        "elevation_m": 1159,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["억새 군락"],
        "description": "영취산과의 사이에 신불평원이라는 광활한 산상 억새초원을 펼친 이색지대다. 동쪽으로는 공룡능선이라는 긴 암봉릉이 뻗어나가 산록 육덕(肉德) 자랑만 하는 주변 산들과 구별된다.",
    },
    {
        "id": "m-가리왕산",
        "name": "가리왕산",
        "region": "강원 정선군",
        "lat": 37.461944,
        "lng": 128.563611,
        "elevation_m": 1562,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "정선아리랑 흐르는 정선의 지붕 강원도 평창군과 정선군은 이 고장 지붕 역할을 하고 있는 가리왕산을 중심으로 험난한 고산준령이 이루어진다고 해도 과언이 아니다.",
    },
    {
        "id": "m-공작산",
        "name": "공작산",
        "region": "강원 홍천군",
        "lat": 37.777778,
        "lng": 127.922222,
        "elevation_m": 887,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소", "계곡 트레킹"],
        "description": "산이 동물 모습을 빼다박으면 영기가 있다고 한다. 영취산, 사자산, 정상부를 봉정이라 불렀던 설악산…. 그래서 자장율사는 이들 기슭에 진신사리를 묻었다.",
    },
    {
        "id": "m-화악산",
        "name": "화악산",
        "region": "경기 가평군",
        "lat": 37.981111,
        "lng": 127.490556,
        "elevation_m": 932,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경기도 최고봉(1468m). 경기 가평 깊숙이 자리한 오지산으로 군사시설 제한 구간이 일부 있다. 중봉에서의 조망이 뛰어나며 울창한 숲길이 사계절 산행객을 맞는다.",
    },
    {
        "id": "m-명지산",
        "name": "명지산",
        "region": "경기 가평군",
        "lat": 37.941389,
        "lng": 127.432778,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경기 가평의 호젓한 산(1267m). 경기도에서 화악산 다음으로 높다. 잣나무 숲과 명지계곡의 맑은 물이 일품이며 북한강 조망이 아름답다. 사람이 적어 조용한 산행을 즐길 수 있다.",
    },
    {
        "id": "m-용문산",
        "name": "용문산",
        "region": "경기 양평군",
        "lat": 37.545556,
        "lng": 127.690278,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경기 양평의 대표 명산(1157m). 천년 넘은 은행나무로 유명한 용문사를 품고 있다. 정상 용문산에서 백운봉·함왕봉으로 이어지는 능선 조망이 탁 트여 시원하다.",
    },
    {
        "id": "m-천마산",
        "name": "천마산",
        "region": "경기 남양주시",
        "lat": 37.611111,
        "lng": 127.413611,
        "elevation_m": 278,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경기 남양주의 대표 산(812m). 수도권에서 접근이 쉬우며 철쭉 군락과 가을 단풍이 아름답다. 산행 후 인근 조안면 카페 거리와 연계하기 좋다.",
    },
    {
        "id": "m-감악산",
        "name": "감악산",
        "region": "경기 파주시",
        "lat": 37.941389,
        "lng": 126.97,
        "elevation_m": 925,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "<span class=\"Apple-style-span\" style=\"widows: 2; text-transform: none; text-indent: 0px; border-collapse: separate; f",
    },
    {
        "id": "m-운악산",
        "name": "운악산",
        "region": "경기 가평군",
        "lat": 37.878333,
        "lng": 127.326389,
        "elevation_m": 935,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관", "단풍 명소", "암릉 경관"],
        "description": "경기5악의 하나인 운악산은 이름에 드러나 있듯 바위가 많은 명산이다. 산봉과 능선이 정상으로 수렴하는 산의 구도도 좋고 바위와 가을 단풍이 어우러진 모양도 아름답다.",
    },
    {
        "id": "m-마이산",
        "name": "마이산",
        "region": "전북 진안군",
        "lat": 35.726944,
        "lng": 127.421944,
        "elevation_m": 687,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.5,
        "national_park": False,
        "highlights": ["암릉 경관"],
        "description": "산이라기보다는 탑으로 부르는 게 더 맞을 기경이다. 영어의 타워와는 완전히 부합한다. 서봉 암마이산과 동봉 숫마이산이 나란히 서있는데 그 모습이 꼭 말의 귀처럼 보인다.",
    },
    {
        "id": "m-조계산",
        "name": "조계산",
        "region": "전남 순천시",
        "lat": 35.031,
        "lng": 127.263,
        "elevation_m": 887,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["사찰 탐방"],
        "description": "드물게도 좌우가 대칭인 산이다. 가운데의 장막골을 축으로 양쪽 산줄기와 물줄기들이 반대방향으로, 같은 수로 뻗어있다. 그 기슭에는 가람이 둘 있다. 승보사찰 송광사와 태고총림 선암사다.",
    },
    {
        "id": "m-두륜산",
        "name": "두륜산",
        "region": "전남 해남군",
        "lat": 34.482,
        "lng": 126.641,
        "elevation_m": 700,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["계곡 트레킹"],
        "description": "가장 남쪽의 '산이라 할 만한 것'이다. 육산 덩어리여서 듬직하기는 하나 잘났다고 할 수는 없다.",
    },
    {
        "id": "m-천관산",
        "name": "천관산",
        "region": "전남 장흥군",
        "lat": 34.655556,
        "lng": 126.901389,
        "elevation_m": 724,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["억새 군락"],
        "description": "비사릿대로 만든 닭의장태 모양의 산이다. 400미터 등고선을 기준으로 하여 산의 얼개를 파악해보면 그 비사릿대, 능선이 스무 개나 된다.",
    },
    {
        "id": "m-대둔산",
        "name": "대둔산",
        "region": "충남 논산시",
        "lat": 36.142,
        "lng": 127.226,
        "elevation_m": 879,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 2,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관"],
        "description": "대둔산은 전북 완주군 운주면과 충남 논산시 벌곡면, 금산군 진산면 사이에 위치한 산이다. 하나의 산을 두고 전북과 충남에서 도립공원으로 지정하였다.",
    },
    {
        "id": "m-서대산",
        "name": "서대산",
        "region": "충남 금산군",
        "lat": 36.29,
        "lng": 127.4475,
        "elevation_m": 905,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소"],
        "description": "900미터가 넘는, 큰 산이 많지 않은 충남에서 가장 높은 산이다. 남북으로 길고 동서로 얇으며 홀로 우뚝, 우람한 비래산(飛來山)이다.",
    },
    {
        "id": "m-오서산",
        "name": "오서산",
        "region": "충남 보령시",
        "lat": 36.551667,
        "lng": 126.815556,
        "elevation_m": 790,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "충남 보령·홍성 경계의 충남 최고봉군(790m). 정상 일대 억새밭이 광활하며 서해 낙조와 함께 펼쳐지는 풍경이 장관이다. 가을 억새 산행지로 명성이 높다.",
    },
    {
        "id": "m-칠갑산",
        "name": "칠갑산",
        "region": "충남 청양군",
        "lat": 36.432222,
        "lng": 126.773889,
        "elevation_m": 560,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "칠갑산. 유장한 능선 골골에 명당갑터 일곱을 감추고있다는 산이다. 600미터도 안 되는 높이에 수더분한 육산인데도 이렇게 대단한 잠재력을 지녔다는 것이다.",
    },
    {
        "id": "m-금정산",
        "name": "금정산",
        "region": "부산 금정구",
        "lat": 35.272222,
        "lng": 129.053611,
        "elevation_m": 801,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.55,
        "national_park": False,
        "highlights": ["설경 명소", "암릉 경관", "정상 전망 우수"],
        "description": "항도 부산의 진산 금정산은 시원한 조망과 아기자기한 산성, 명찰 범어사가 어우러진 산이다. 금정산이란 이름은 산꼭대기에 금빛을 띤, 샘이 있다는 데서 유래한다.",
    },
    {
        "id": "m-토함산",
        "name": "토함산",
        "region": "경북 경주시",
        "lat": 35.792778,
        "lng": 129.350833,
        "elevation_m": 746,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 4,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경북 경주의 신라 영산(745m). 불국사와 석굴암을 산자락에 품고 있으며 산 이름은 '구름을 머금는다'는 뜻이다. 동해를 향한 일출 조망으로도 유명하다.",
    },
    {
        "id": "m-내연산",
        "name": "내연산",
        "region": "경북 포항시",
        "lat": 36.111944,
        "lng": 129.369444,
        "elevation_m": 711,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["계곡 트레킹"],
        "description": "낙동정맥 줄기가 주왕산을 옆으로 지나쳐 내려오다가 동해안 쪽으로 뻗어가 솟은 산이 바로 내연산이다.",
    },
    {
        "id": "m-방태산",
        "name": "방태산",
        "region": "강원 인제군",
        "lat": 38.001944,
        "lng": 128.362222,
        "elevation_m": 1446,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "강원 인제의 식물 생태 보고(1444m). 우리나라에서 자생 식물 종류가 가장 많은 산으로 꼽힌다. 개인약수·방동약수가 인근에 있으며 사람의 발길이 적어 원시림 분위기를 간직하고 있다.",
    },
    {
        "id": "m-점봉산",
        "name": "점봉산",
        "region": "강원 양양군",
        "lat": 38.047778,
        "lng": 128.408889,
        "elevation_m": 1426,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 1,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["단풍 명소", "설경 명소", "정상 전망 우수"],
        "description": "오색약수 품은 설악산 전망대> 점봉산은 오색온천과 약수를 끼고 있긴 하지만 설악의 그늘에 가려 그 위풍을 펴지 못했었다.",
    },
    {
        "id": "m-대암산",
        "name": "대암산",
        "region": "강원 인제군",
        "lat": 38.188056,
        "lng": 128.1625,
        "elevation_m": 1313,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "고층습원으로 잘 알려진 대암산은 정상부근에 있는 분지형으로 된 큰 용늪과 작은 용늪이 있다.",
    },
    {
        "id": "m-백덕산",
        "name": "백덕산",
        "region": "강원 영월군",
        "lat": 37.391667,
        "lng": 128.326944,
        "elevation_m": None,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "강원 영월의 백두대간 곁가지 고봉(1350m). 정상부 주목 군락이 유명하며 사자산·중왕산과 능선이 이어진다. 눈 쌓인 주목 설경이 아름다워 겨울 산행지로도 인기가 있다.",
    },
    {
        "id": "m-청옥산",
        "name": "청옥산",
        "region": "강원 삼척시",
        "lat": 37.371389,
        "lng": 129.053889,
        "elevation_m": None,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "강원 삼척의 백두대간 고봉(1404m). 두타산과 맞닿아 무릉계곡 상류를 품고 있다. 두타산과 함께 종주하는 무릉계곡 산행이 이 일대 최고의 코스로 꼽힌다.",
    },
    {
        "id": "m-선자령",
        "name": "선자령",
        "region": "강원 평창군",
        "lat": 37.7125,
        "lng": 128.712778,
        "elevation_m": 1157,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "강원 평창 대관령 능선의 고원 트레킹 명소(1157m). 드넓은 초원과 풍력발전기 군락이 이국적 풍경을 만들어낸다. 겨울 설원과 여름 목장 능선 모두 아름답다.",
    },
    {
        "id": "m-용화산",
        "name": "용화산",
        "region": "강원 춘천시",
        "lat": 37.901111,
        "lng": 127.831944,
        "elevation_m": 878,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소", "암릉 경관", "사찰 탐방"],
        "description": "용화산은 강원도 춘천시 사북면과 화천군 하남면 경계에 솟은 바위산이자 춘천의 의암댐, 소양댐, 춘천댐, 화천댐에 포위된 천혜의 성벽이다.",
    },
    {
        "id": "m-삼악산",
        "name": "삼악산",
        "region": "강원 춘천시",
        "lat": 37.888333,
        "lng": 127.820833,
        "elevation_m": 656,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관", "사찰 탐방"],
        "description": "삼악산은 등선봉, 청운봉에서 이어지는 한 봉우리다. 강촌의 대표적인 산으로 하나의 독립봉으로 사람들이 즐겨 찾고 있으며 접근이 용이하여 당일산행지로서 각광받고 있다.",
    },
    {
        "id": "m-인왕산",
        "name": "인왕산",
        "region": "서울 종로구",
        "lat": 37.584722,
        "lng": 126.957778,
        "elevation_m": 340,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.72,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "서울 종로·서대문에 걸친 바위산(338m). 화강암 기암 능선을 따라 한양도성 성곽길이 이어지며 수성동계곡, 범바위 등 볼거리가 풍부하다. 도심 속 역사 산행지로 인기 높다.",
    },
    {
        "id": "m-아차산",
        "name": "아차산",
        "region": "서울 광진구",
        "lat": 37.573056,
        "lng": 127.103333,
        "elevation_m": 287,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.7,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "서울 광진·경기 구리 경계의 낮은 산(296m). 고구려 성곽 유적이 능선을 따라 이어지며 한강과 서울 도심을 내려다보는 조망이 탁월하다. 역사 탐방과 가벼운 산책 코스로 인기 높다.",
    },
    {
        "id": "m-수락산",
        "name": "수락산",
        "region": "서울 노원구",
        "lat": 37.699167,
        "lng": 127.083889,
        "elevation_m": 641,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.38,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경기 의정부·서울 노원 경계의 기암 명산(638m). 화강암 암릉과 맑은 계곡이 어우러져 수도권 암릉 산행지로 인기가 높다. 도봉산·불암산과 이어지는 능선 종주 코스도 유명하다.",
    },
    {
        "id": "m-불암산",
        "name": "불암산",
        "region": "서울 노원구",
        "lat": 37.663889,
        "lng": 127.095833,
        "elevation_m": 510,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.42,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경기 남양주·서울 노원의 화강암 바위산(508m). 정상부 불암(佛巖)이라 불리는 대형 암벽이 특징이다. 수락산과 능선으로 이어져 함께 종주하는 코스로 즐겨 찾는다.",
    },
    {
        "id": "m-청계산",
        "name": "청계산",
        "region": "서울 서초구",
        "lat": 37.4275,
        "lng": 127.055,
        "elevation_m": 849,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.65,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경기 성남·과천에 걸친 수도권 대표 근교산(618m). 매봉·옥녀봉·이수봉 등 봉우리마다 조망이 좋고 코스가 다양하다. 주말이면 수도권 최다 등산객이 찾는 산 중 하나다.",
    },
    {
        "id": "m-광교산",
        "name": "광교산",
        "region": "경기 수원시",
        "lat": 37.316944,
        "lng": 127.044722,
        "elevation_m": 582,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경기 수원·용인 경계의 산(582m). 광교호수공원과 이어지는 산행이 가능하며 봄 철쭉 군락이 명물이다. 도심과 가까운 덕분에 사시사철 시민들의 발길이 끊이지 않는다.",
    },
    {
        "id": "m-달마산",
        "name": "달마산",
        "region": "전남 해남군",
        "lat": 34.527222,
        "lng": 126.53,
        "elevation_m": 499,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "전남 해남 땅끝 인근의 기암 명산(489m). 달마고도라는 둘레길이 개설되어 있으며 미황사를 품고 있다. 빼어난 암릉 능선 위로 다도해 풍경이 펼쳐진다.",
    },
    {
        "id": "m-가리산",
        "name": "가리산",
        "region": "강원 홍천군",
        "lat": 37.779167,
        "lng": 128.012778,
        "elevation_m": 774,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "강원 홍천의 깊은 오지산(1051m). 두꺼운 침엽수림과 계곡 물소리가 청정한 강원 산행의 묘미를 선사한다. 가리왕산과 혼동하기 쉬우나 별개의 산이다.",
    },
    {
        "id": "m-응봉산",
        "name": "응봉산",
        "region": "강원 삼척시",
        "lat": 37.235,
        "lng": 129.091111,
        "elevation_m": 1268,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "강원 삼척의 백두대간 산(998m). 환선굴로 향하는 덕항산 인근에 자리하며 조용하고 호젓한 산행이 가능하다. 삼척 동해 방향 조망이 맑은 날 시원하게 펼쳐진다.",
    },
    {
        "id": "m-대야산",
        "name": "대야산",
        "region": "경북 문경시",
        "lat": 36.661111,
        "lng": 128.179722,
        "elevation_m": 931,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 1,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["계곡 트레킹"],
        "description": "백화산과 희양산을 지나 속리산 사이에 솟은 대야산은 속리산국립공원내에 포함되며, 백두대간 상의 산으로 경북과 충북 양쪽에 내외 선유동을 두고 있을 정도로 계곡이 특히 유명하다.",
    },
    {
        "id": "m-장안산",
        "name": "장안산",
        "region": "전북 장수군",
        "lat": 35.719444,
        "lng": 127.646111,
        "elevation_m": 1237,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["단풍 명소", "계곡 트레킹", "억새 군락"],
        "description": "장안산은 금남정맥과 호남정맥을 거느리며 백두대간의 기운을 충청도와 전라도에 전하는 호남의 종산이다.",
    },
    {
        "id": "m-천성산",
        "name": "천성산",
        "region": "경남 양산시",
        "lat": 35.459444,
        "lng": 129.074722,
        "elevation_m": 920,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "\"\"가파른 연봉들 첩첩이요 깊고 깊은 골짜기 굴 같다(連峰疊 洞府深邃)\"\"는 산이다.",
    },
    {
        "id": "m-연화산",
        "name": "연화산",
        "region": "경남 고성군",
        "lat": 34.984444,
        "lng": 128.115556,
        "elevation_m": 1172,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경남 고성의 온화한 산(528m). 신라 고찰 옥천사를 품고 있으며 연꽃 모양의 산세에서 이름을 따왔다. 남해안 특유의 부드러운 능선과 사찰 경관이 조화롭다.",
    },
    {
        "id": "m-팔영산",
        "name": "팔영산",
        "region": "전남 고흥군",
        "lat": 34.637222,
        "lng": 127.415556,
        "elevation_m": 607,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 1,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "전남 고흥 다도해 국립공원의 암봉 명산(608m). 일(一)봉부터 팔(八)봉까지 여덟 개 암봉이 병풍처럼 솟아 있으며 봉우리마다 다도해 섬들이 그림처럼 펼쳐진다.",
    },
    {
        "id": "m-무학산",
        "name": "무학산",
        "region": "경남 창원시",
        "lat": 35.198056,
        "lng": 128.561944,
        "elevation_m": 200,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경남 창원 마산의 진산(761m). 창원·마산 도심과 진해만을 한눈에 내려다볼 수 있는 조망 명산이다. 두척산과 이어지는 능선 종주 코스가 인기 있다.",
    },
    {
        "id": "m-화왕산",
        "name": "화왕산",
        "region": "경남 창녕군",
        "lat": 35.502778,
        "lng": 128.501944,
        "elevation_m": 758,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["억새 군락"],
        "description": "창녕읍의 진산으로 관룡산과 더불어 화왕산 군립공원을 이룬다. 화왕산 하면 억새를 떠올릴 만큼 억새의 대명사이기도 하다. ６만여평의 대평원에 십리 억새밭.",
    },
    {
        "id": "m-가지산",
        "name": "가지산",
        "region": "경남 밀양시",
        "lat": 35.623056,
        "lng": 129.058611,
        "elevation_m": 1241,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "부산산악인들이 이름붙인 영남알프스는 낙동정맥 아랫부분의 천 미터 넘는 산들을 총칭하는 개념이다.",
    },
    {
        "id": "m-문복산",
        "name": "문복산",
        "region": "경북 청도군",
        "lat": 35.673889,
        "lng": 129.040278,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경북 청도의 영남알프스 권역 산(1015m). 운문산 북쪽에 자리하며 조용하고 호젓한 숲 산행을 즐길 수 있다. 능선에서 가지산·운문산 방향 전망이 좋다.",
    },
    {
        "id": "m-영축산",
        "name": "영축산",
        "region": "경남 양산시",
        "lat": 35.464722,
        "lng": 129.019444,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경남 양산의 영남알프스 주봉(1059m). 신불산 방향으로 이어지는 광활한 신불평원 억새 초원이 장관이다. 통도사를 산자락에 품은 불교 성지이기도 하다.",
    },
    {
        "id": "m-고헌산",
        "name": "고헌산",
        "region": "경남 울주군",
        "lat": 35.563056,
        "lng": 129.124167,
        "elevation_m": 1033,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "경남 울주 영남알프스 서편 끝자락(1033m). 가지산과 마주 보며 조용한 산세를 지닌다. 정상부 암릉에서 울산만과 영남알프스 주능선이 한눈에 들어온다.",
    },
    {
        "id": "m-황석산",
        "name": "황석산",
        "region": "경남 함양군",
        "lat": 35.601,
        "lng": 127.762,
        "elevation_m": 1193,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["암릉 경관", "계곡 트레킹", "억새 군락"],
        "description": "경남 거창 남쪽의 기암 바위산(1190m). 병풍처럼 선 거대한 암벽과 황석산성 유적이 인상적이다. 거창 남상면에서 바라보면 하늘을 찌를 듯 솟아오른 웅장한 자태가 압도적이다.",
    },
]

MOUNTAIN_BY_ID = {m['id']: m for m in MOUNTAINS}
MOUNTAIN_BY_NAME = {m['name']: m for m in MOUNTAINS}
