# 산림청 API 자동 수집 — collect_mountains2.py

MOUNTAINS = [
    {
        "id": "m-설악산",
        "name": "설악산",
        "region": "강원 속초시",
        "lat": 38.119444,
        "lng": 128.465556,
        "elevation_m": 1708,
        "difficulty": "hard",
        "walk_time_min": 360,
        "walk_time_max": 720,
        "trail_count": 13,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view", "workout"],
        "crowding": 0.68,
        "national_park": True,
        "highlights": ["국립공원", "설경 명소"],
        "description": "한마디로 한국의 알프스다. 흔히 금강산에 비유하지만 높이도 72미터나 낮고 동서로 긴 능선이 없어 산역은 훨씬 좁다. 그럼에도 금강산이 예로부터 더 유명했던 이유는 교통이 편리한 데다 짚신 신고도 못 올라갈 데가 거의 없을 만큼 산이",
    },
    {
        "id": "m-지리산",
        "name": "지리산",
        "region": "경남 산청군",
        "lat": 35.336944,
        "lng": 127.730556,
        "elevation_m": 1915,
        "difficulty": "hard",
        "walk_time_min": 360,
        "walk_time_max": 720,
        "trail_count": 34,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view", "workout"],
        "crowding": 0.55,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "지리산은 크다. 높고도 넓고 그리고 깊다. 3도 여섯 고을―함양, 산청, 하동, 구례, 남원, 운봉[현]에 그림자 드리운 거대한 산국(山國)이다. 1000미터 이상의 주릉만 해도 110리나 된다. 실상사 서쪽 덕두산(1151.5m)에",
    },
    {
        "id": "m-한라산",
        "name": "한라산",
        "region": "제주 제주시",
        "lat": 33.361667,
        "lng": 126.529167,
        "elevation_m": 1947,
        "difficulty": "hard",
        "walk_time_min": 360,
        "walk_time_max": 720,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view", "workout"],
        "crowding": 0.7,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "한반도 남쪽의 최고봉, 해발 1950m의 한라산은 제주도 사람들의 숨결과 역사를 그대로 안고 있는 산이다. 한라산이란 이름은 원래 '은하수를 끌어당길 수 있다(雲漢可拏引也)'는 뜻으로 붙여진 이름이다. 그만큼 산이 높다는 점을 강조한",
    },
    {
        "id": "m-북한산",
        "name": "북한산",
        "region": "서울 강북구",
        "lat": 37.658611,
        "lng": 126.977389,
        "elevation_m": 836,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 59,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.82,
        "national_park": True,
        "highlights": ["국립공원", "설경 명소"],
        "description": "북한산은 성채다. 최고봉 백운대를 비롯하여 인수봉, 노적봉, 의상봉, 보현봉 등 걸출한 암봉들이 험준한 산세를 이루고 여기 의지하여 사람들이 진짜 성을 쌓았다. 썩 높은 산은 아니지만 주변에 어깨를 겨룰 대상이 없어 눈 닿는 곳이면 ",
    },
    {
        "id": "m-오대산",
        "name": "오대산",
        "region": "강원 평창군",
        "lat": 37.794444,
        "lng": 128.543611,
        "elevation_m": 1565,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 27,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "healing", "workout"],
        "crowding": 0.48,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "다섯 개의 봉우리를 가진 산이란 뜻의 오대산은 동서 20km, 남북 33km, 660㎢의 광대한 면적을 자랑한다. 주봉인 비로봉(1565.4m)을 중심으로 상왕봉(1493m), 호령봉(1565.5m), 두로봉(1422.7m), 동대산",
    },
    {
        "id": "m-소백산",
        "name": "소백산",
        "region": "충북 단양군",
        "lat": 36.957778,
        "lng": 128.484444,
        "elevation_m": 1440,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 11,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "소백산(1439.7m)은 백두대간이 거느린 명산 중 하나다. 동쪽에서부터 국망봉, 비로봉, 연화봉, 죽령 너머의 도솔봉 등 1000m가 넘는 봉을 연결하는 장쾌한 능선이 20km 이상 뻗어 있다. 이중 도솔봉을 제외한, 소백의 삼봉(",
    },
    {
        "id": "m-태백산",
        "name": "태백산",
        "region": "강원 태백시",
        "lat": 37.095833,
        "lng": 128.916667,
        "elevation_m": 1567,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 10,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "신라 임금이 둘씩이나 순행을 갔던 성산(聖山)이다. 그때는 물론 봉화 태백산이었는 바 기실은 그쪽이 태백산의 정면이다. 산의 대부분이 그 영역인 북쪽의 태백시는 구한말 비결파들이 몰려들기 전까지는 무인지경이었다. 남쪽에서 본 산의 모",
    },
    {
        "id": "m-치악산",
        "name": "치악산",
        "region": "강원 원주시",
        "lat": 37.365,
        "lng": 128.055556,
        "elevation_m": 1282,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 4,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.45,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "명산은 가까이 가보면 안다. 영동고속국도 원주를 지날 무렵 뭇 산을 제압하는 훤칠한 산이 보인다면 물어볼 것도 없이 치악산인 것이다. 들고을 원주(原州)에서 보면 그건 거대한 장벽이다. 17킬로미터의 장대한 주릉이 그대로 천여미터를 ",
    },
    {
        "id": "m-월악산",
        "name": "월악산",
        "region": "충북 제천시",
        "lat": 36.889444,
        "lng": 128.105556,
        "elevation_m": 1095,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 10,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.42,
        "national_park": True,
        "highlights": ["국립공원", "설경 명소", "사찰 탐방"],
        "description": "월악산(1095.3m)은 설악산의 현란한 아름다움과 지리산의 장엄함을 조금씩 가져다 놓은 듯한 산세를 지녔다. 깎아지른 절벽이 가슴 조이게 하지만 부드러운 능선의 푸근함도 함께 주는 산이다. 국사봉으로도 부르는 월악산의 정상은 예로부",
    },
    {
        "id": "m-속리산",
        "name": "속리산",
        "region": "충북 보은군",
        "lat": 36.543056,
        "lng": 127.870833,
        "elevation_m": 1058,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 12,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.52,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "속리산은 1970년 국립공원으로 지정된 대한팔경 중 하나다. 주봉인 천황봉(1058.4m)을 비롯해 비로봉, 길상봉, 문수봉 등 8봉과 입석대, 문장대, 신선대 같이 빼어난 자태를 자랑하며 우뚝 솟은 8대8석문이 활처럼 휘어져 자리하",
    },
    {
        "id": "m-계룡산",
        "name": "계룡산",
        "region": "충남 공주시",
        "lat": 36.342778,
        "lng": 127.205556,
        "elevation_m": 847,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 8,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.55,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "계룡산은 수려한 산세와 승지 신도안, 여러 고찰들을 품은 충남 제일의 명산이다. 이미 신라시대 5악의 하나였고 조선시대에는 묘향산, 지리산과 함께 산신제를 올리던 영산이었다. 주봉인 천황봉에서 쌀개봉으로 이어지는 능선미가 타의 추종을",
    },
    {
        "id": "m-덕유산",
        "name": "덕유산",
        "region": "전북 무주군",
        "lat": 35.859722,
        "lng": 127.746389,
        "elevation_m": 1507,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 3,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.45,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "&nbsp;",
    },
    {
        "id": "m-가야산",
        "name": "가야산",
        "region": "경남 합천군",
        "lat": 35.823611,
        "lng": 128.120833,
        "elevation_m": 678,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 2,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.55,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "가야산 — 경남 합천군 위치 명산.",
    },
    {
        "id": "m-내장산",
        "name": "내장산",
        "region": "전북 정읍시",
        "lat": 35.478333,
        "lng": 126.8875,
        "elevation_m": 764,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 5,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.58,
        "national_park": True,
        "highlights": ["국립공원", "단풍 명소"],
        "description": "우리나라에서 \"\"단풍\"\" 하면 제일 먼저 떠오르는 산이 바로 내장산이다. 동구부터 내장사까지 3킬로미터 남짓 되는 길가가 온통 단풍나무밭이다. 그래 단풍철이면 산 안통이 사람들로 인산인해를 이룬다. 단풍놀이를 온 사람들은 대개 골짜기",
    },
    {
        "id": "m-무등산",
        "name": "무등산",
        "region": "광주 동구",
        "lat": 35.134167,
        "lng": 126.988889,
        "elevation_m": 1187,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 14,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.58,
        "national_park": True,
        "highlights": ["국립공원", "암릉 경관"],
        "description": "무등산은 산줄기와 골짜기가 뚜렷하지 않고 마치 커다란 둔덕과 같은 산세를 지닌 홑산이다. 가장 큰 특징은 너덜지대로, 천왕봉 남쪽의 지공너덜과 증심사 동쪽의 덕산너덜은 장관을 자랑한다. 천태만상의 암석들이 운집한 정상, 천왕봉을 중심",
    },
    {
        "id": "m-주왕산",
        "name": "주왕산",
        "region": "경북 청송군",
        "lat": 36.389444,
        "lng": 129.163611,
        "elevation_m": 722,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 5,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.48,
        "national_park": True,
        "highlights": ["국립공원", "폭포 경관", "설경 명소", "사찰 탐방"],
        "description": "하늘을 나는 재주 없이는 들어갈 수 없는 동천(洞天). 협곡의 입구로는 급류가 쏟아나오고 깎아지른 양쪽 절벽은 높이를 가늠할 수 없다. 무협소설에나 등장함직한 풍경. 그렇지만 이땅에도 그런 산이 있었다. 70년대의 어리석은 사람들이 ",
    },
    {
        "id": "m-월출산",
        "name": "월출산",
        "region": "전남 영암군",
        "lat": 34.765,
        "lng": 126.704444,
        "elevation_m": 811,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 3,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.42,
        "national_park": True,
        "highlights": ["국립공원"],
        "description": "프랑스의 세계문화유산 몽쌩미쉘(Mont Saint-Michel) 같은 산이다. 정상 천황봉만 떼어 보면 피라밋 같기도 하다. 천황사쪽 평균경사 37도. 이땅에서 이보다 가파른 산은 없다. 천황봉은 물론이고 향로봉, 양자봉, 시루봉, ",
    },
    {
        "id": "m-팔공산",
        "name": "팔공산",
        "region": "대구 동구",
        "lat": 35.992,
        "lng": 128.686,
        "elevation_m": 1192,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 7,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.6,
        "national_park": True,
        "highlights": ["국립공원", "암릉 경관", "사찰 탐방"],
        "description": "신라의 중악(中岳) 팔공산은 대구산악인의 모산이며 약사신앙의 1번지다. 이름은 대구, 칠곡, 인동(현 구미 인의동 일대), 신녕, 의흥, 영천, 하양, 경산 등 여덟 마을에 걸쳐 있어 붙여졌다. 가산에서 갓바위까지 주릉만 26km다.",
    },
    {
        "id": "m-도봉산",
        "name": "도봉산",
        "region": "서울 도봉구",
        "lat": 37.698056,
        "lng": 127.015278,
        "elevation_m": 740,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.78,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "봉만미(峰巒美)가 탁월하게 빼어난 산이다. \"\"푸른 하늘 깎아세운 만 길 봉우리(靑天削出萬丈峰)\"\"라 읊었던 옛 시인의 표현이 무릎을 치게 만드는 장쾌한 선인봉을 비롯해 그 뒤에 중첩된 만장봉, 자운봉, 신선봉, 서쪽 끝의 기이한 다",
    },
    {
        "id": "m-관악산",
        "name": "관악산",
        "region": "서울 관악구",
        "lat": 37.4451398,
        "lng": 126.9642379,
        "elevation_m": 632,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.75,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "옛 과천현의 진산이지만 정면은 서울쪽이다. 거기다 산세가 화성(火星)의 극치를 이뤄 불꽃 너울이 상봉으로 수렴, 하늘을 태우는 듯하다. 해질녁에 뚝섬쪽에서 보면 정말 불 붙은 듯한 바 광화문 앞에 해태상을 둔 이유는 그 불기운이 경복",
    },
    {
        "id": "m-두타산",
        "name": "두타산",
        "region": "강원 동해시",
        "lat": 37.4266369,
        "lng": 129.0044248,
        "elevation_m": 1357,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view", "workout"],
        "crowding": 0.35,
        "national_park": False,
        "highlights": ["폭포 경관", "암릉 경관", "계곡 트레킹"],
        "description": "계곡 이름을 무릉계(武陵溪)라고 했다. 얼마나 대단한 경치면 감히 “무릉도원은 바로 여기”라고 내세웠다. 두타산과 청옥산, 고적대, 갈미봉, 1243봉으로 둘러싸인 반석계곡이다. 가보면 고개를 끄덕이게될 것이다. 벼루처럼 매끄러운 바",
    },
    {
        "id": "m-함백산",
        "name": "함백산",
        "region": "강원 태백시",
        "lat": 37.161159,
        "lng": 128.917602,
        "elevation_m": 1573,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 2,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.32,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-민주지산",
        "name": "민주지산",
        "region": "충북 영동군",
        "lat": 36.0397937,
        "lng": 127.8492728,
        "elevation_m": 1242,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["계곡 트레킹"],
        "description": "민주지산(1241.7m)은 충북, 경북, 전북 등 3도에 걸쳐 있다. 동으로는 석기봉과 삼도봉, 북으로는 각호산이 좌우로 날개처럼 우뚝 솟아올라 웅장한 기상을 펼치며 백두대간을 굽어보는 산이다. '동국여지승람'과 '대동여지도'에는 백",
    },
    {
        "id": "m-황매산",
        "name": "황매산",
        "region": "경남 합천군",
        "lat": 35.519,
        "lng": 127.976,
        "elevation_m": 1113,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.35,
        "national_park": False,
        "highlights": ["철쭉 명소", "억새 군락"],
        "description": "합천호반을 지나다 보면 남쪽 하늘금에 굉장한 산 하나가 솟아있다. 이 근처에도 저런 높은 산이 있었나 싶을 만큼 준걸한 암봉이 호숫물에 어린다. 지도를 펴보면… 황매산이다. 자료를 찾아보면… 하늘금만 이쁜 게 아니고 억새와 철쭉도 유",
    },
    {
        "id": "m-금오산",
        "name": "금오산",
        "region": "경북 구미시",
        "lat": 36.142,
        "lng": 128.318,
        "elevation_m": 634,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-비슬산",
        "name": "비슬산",
        "region": "대구 달성군",
        "lat": 35.715597,
        "lng": 128.5231844,
        "elevation_m": 1083,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["암릉 경관"],
        "description": "대구를 분지로 만드는 두 산은 팔공산과 비슬산이다. 화강암질의 팔공산이 산세가 웅장하여 아버지 산이라면 안산암질의 비슬산은 온화하고 부드러워 어머니 산이라 할 만하다. 비슬산은 우리나라에서 다섯 손가락에 꼽는 진달래 명산이다. 평탄한",
    },
    {
        "id": "m-운문산",
        "name": "운문산",
        "region": "경북 청도군",
        "lat": 35.6155103,
        "lng": 128.9596632,
        "elevation_m": 1195,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["암릉 경관", "정상 전망 우수"],
        "description": "거울에 비친 下자형 산줄기 영남알프스의 윗금 서쪽끝을 이루는 산이다. 거대한 봉분 같은 단순한 모양새이지만 억산과 가지산의 좌우 준봉에서 북으로 뻗어간 긴 능선들 덕분에 운문사 들어앉은 깊은 골을 갖추었다. 그러나 남쪽으로는 여지없는",
    },
    {
        "id": "m-재약산",
        "name": "재약산",
        "region": "경남 밀양시",
        "lat": 35.5454243,
        "lng": 128.9806162,
        "elevation_m": 1119,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["사찰 탐방"],
        "description": "왼손으로 쓴 下자 형국 영남알프스의 점에 해당하는 산이다. 그만큼 깊이 숨어있는 산중 속의 산으로 빙 둘러 타원형 능선이 길지를 품고있다. 표충사. 국보 75호 청동함은향완(含銀香玩)과 보물 467호 삼층석탑, 사명대사 유물 200여",
    },
    {
        "id": "m-신불산",
        "name": "신불산",
        "region": "경남 울주군",
        "lat": 35.5394127,
        "lng": 129.0540979,
        "elevation_m": 1159,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관", "억새 군락"],
        "description": "영취산과의 사이에 신불평원이라는 광활한 산상 억새초원을 펼친 이색지대다. 동쪽으로는 공룡능선이라는 긴 암봉릉이 뻗어나가 산록 육덕(肉德) 자랑만 하는 주변 산들과 구별된다. 그럼에도 썩 튀지는 않아 간월, 가지, 상운, 고헌의 천미터",
    },
    {
        "id": "m-가리왕산",
        "name": "가리왕산",
        "region": "강원 정선군",
        "lat": 37.461944,
        "lng": 128.563611,
        "elevation_m": 1562,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "정선아리랑 흐르는 정선의 지붕 강원도 평창군과 정선군은 이 고장 지붕 역할을 하고 있는 가리왕산을 중심으로 험난한 고산준령이 이루어진다고 해도 과언이 아니다. 정선의 주산 가리왕산은 갈왕(葛王)이 난을 피하여 숨어든 곳이라 하여 갈왕",
    },
    {
        "id": "m-공작산",
        "name": "공작산",
        "region": "강원 홍천군",
        "lat": 37.7159579,
        "lng": 128.0106651,
        "elevation_m": 887,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소"],
        "description": "산이 동물 모습을 빼다박으면 영기가 있다고 한다. 영취산, 사자산, 정상부를 봉정이라 불렀던 설악산…. 그래서 자장율사는 이들 기슭에 진신사리를 묻었다. 하지만 진신사리가 다 떨어졌을 때 그런 산이 발견되었다면 무릎을 칠 수밖에 없었",
    },
    {
        "id": "m-화악산",
        "name": "화악산",
        "region": "경기 가평군",
        "lat": 37.9946674,
        "lng": 127.5034314,
        "elevation_m": 932,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "화악산 — 경기 가평군 위치 명산.",
    },
    {
        "id": "m-명지산",
        "name": "명지산",
        "region": "경기 가평군",
        "lat": 37.941389,
        "lng": 127.432778,
        "elevation_m": 1252,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소", "사찰 탐방"],
        "description": "명지산은 하늘금 이쁜 명산은 아니지만 높고 깊은 맛이 있다. 경기도에서 가장 산이 많고 지대가 높은 가평군에 자리한 제2봉이기 때문이다. 특히 남쪽의 청우산(617.8m)에서 시작, 대금산(705.8m), 매봉(929.2m), 연인산",
    },
    {
        "id": "m-용문산",
        "name": "용문산",
        "region": "경기 양평군",
        "lat": 37.545556,
        "lng": 127.690278,
        "elevation_m": 1157,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소"],
        "description": "용문산은 경인지역에서 설악산 갈 때 보게되는 큰 산이다. 44번 국도변에는 이보다 더 높은 산도 많지만 대개는 골짜기를 따라 이어진 도로에서 올려다보게 되어있어 규모를 느낄 수 없다. 그러나 용문산은 비산비야의 용문면 북쪽 끝에 병풍",
    },
    {
        "id": "m-천마산",
        "name": "천마산",
        "region": "경기 남양주시",
        "lat": 37.6802108,
        "lng": 127.2733462,
        "elevation_m": 278,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-감악산",
        "name": "감악산",
        "region": "경기 파주시",
        "lat": 37.941389,
        "lng": 126.97,
        "elevation_m": 925,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소"],
        "description": "&nbsp;거창의 안산이다. 거창군 남상면과 신원면의 경계를 이룬다. 정상에 넓은 감악평전이 있고 KBS MBC 방송중계탑과 이동통신중계탑 등이 설치되어 있다. 신라 애장왕 3년 이 산에 연수사를 세운 감악조사의 이름을 따라 감악산이",
    },
    {
        "id": "m-운악산",
        "name": "운악산",
        "region": "경기 가평군",
        "lat": 37.87869,
        "lng": 127.32288,
        "elevation_m": 935,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관", "단풍 명소", "암릉 경관"],
        "description": "경기5악의 하나인 운악산은 이름에 드러나 있듯 바위가 많은 명산이다. 산봉과 능선이 정상으로 수렴하는 산의 구도도 좋고 바위와 가을 단풍이 어우러진 모양도 아름답다. 그래서 '경기의 금강'으로 불린다. 동쪽 기슭에는 보조국사 지눌의 ",
    },
    {
        "id": "m-마이산",
        "name": "마이산",
        "region": "전북 진안군",
        "lat": 35.726944,
        "lng": 127.421944,
        "elevation_m": 687,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.5,
        "national_park": False,
        "highlights": ["암릉 경관"],
        "description": "산이라기보다는 탑으로 부르는 게 더 맞을 기경이다. 영어의 타워와는 완전히 부합한다. 서봉 암마이산과 동봉 숫마이산이 나란히 서있는데 그 모습이 꼭 말의 귀처럼 보인다. 남북으로 높은 산이 없어 더욱 장관으로 진안 우주들이나 사양제 ",
    },
    {
        "id": "m-조계산",
        "name": "조계산",
        "region": "전남 순천시",
        "lat": 35.031,
        "lng": 127.263,
        "elevation_m": 887,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["사찰 탐방"],
        "description": "드물게도 좌우가 대칭인 산이다. 가운데의 장막골을 축으로 양쪽 산줄기와 물줄기들이 반대방향으로, 같은 수로 뻗어있다. 그 기슭에는 가람이 둘 있다. 승보사찰 송광사와 태고총림 선암사다. 상봉 장군봉 코밑의 선암사는 옥 같은 미녀가 잔",
    },
    {
        "id": "m-두륜산",
        "name": "두륜산",
        "region": "전남 해남군",
        "lat": 34.482,
        "lng": 126.641,
        "elevation_m": 700,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["계곡 트레킹"],
        "description": "가장 남쪽의 '산이라 할 만한 것'이다. 육산 덩어리여서 듬직하기는 하나 잘났다고 할 수는 없다. 그런데도 산 보는 데 일가견이 있던 서산대사가 자신의 의발(衣鉢)―옷가지와 밥그릇을 여기 갖다노라 한 것을 보면 뭔가 있기는 한 듯하다",
    },
    {
        "id": "m-천관산",
        "name": "천관산",
        "region": "전남 장흥군",
        "lat": 34.6372,
        "lng": 126.9014,
        "elevation_m": 724,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["억새 군락"],
        "description": "비사릿대로 만든 닭의장태 모양의 산이다. 400미터 등고선을 기준으로 하여 산의 얼개를 파악해보면 그 비사릿대, 능선이 스무 개나 된다. 하여 전체적으로 거대한 돔을 이루어 보는 이를 압도한다. 시월 첫째주말에 억새제를 열 만큼 억새",
    },
    {
        "id": "m-대둔산",
        "name": "대둔산",
        "region": "충남 논산시",
        "lat": 36.142,
        "lng": 127.226,
        "elevation_m": 879,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 2,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "대둔산은 전북 완주군 운주면과 충남 논산시 벌곡면, 금산군 진산면 사이에 위치한 산이다. 하나의 산을 두고 전북과 충남에서 도립공원으로 지정하였다. 이 산은 최고봉인 마천대를 중심으로 기암괴석들이 제각기 위용을 자랑하며 늘어서 있고,",
    },
    {
        "id": "m-서대산",
        "name": "서대산",
        "region": "충남 금산군",
        "lat": 36.29,
        "lng": 127.4475,
        "elevation_m": 905,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "900미터가 넘는, 큰 산이 많지 않은 충남에서 가장 높은 산이다. 남북으로 길고 동서로 얇으며 홀로 우뚝, 우람한 비래산(飛來山)이다. 그러나 기슭에 개활지를 이루는 평야가 없으며 동쪽으로는 장룡산(654.5m), 매봉(599.5m",
    },
    {
        "id": "m-오서산",
        "name": "오서산",
        "region": "충남 보령시",
        "lat": 36.551667,
        "lng": 126.815556,
        "elevation_m": 790,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "오서산 — 충남 보령시 위치 명산.",
    },
    {
        "id": "m-칠갑산",
        "name": "칠갑산",
        "region": "충남 청양군",
        "lat": 36.4130234,
        "lng": 126.8848823,
        "elevation_m": 560,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "칠갑산. 유장한 능선 골골에 명당갑터 일곱을 감추고있다는 산이다. 600미터도 안 되는 높이에 수더분한 육산인데도 이렇게 대단한 잠재력을 지녔다는 것이다. 주릉이 5방으로 뻗어나간 산세나 청양 분지에서 비롯하는 아흔아홉골 지천(芝川)",
    },
    {
        "id": "m-금정산",
        "name": "금정산",
        "region": "부산 금정구",
        "lat": 35.272222,
        "lng": 129.053611,
        "elevation_m": 801,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.55,
        "national_park": False,
        "highlights": ["설경 명소", "암릉 경관", "정상 전망 우수"],
        "description": "항도 부산의 진산 금정산은 시원한 조망과 아기자기한 산성, 명찰 범어사가 어우러진 산이다. 금정산이란 이름은 산꼭대기에 금빛을 띤, 샘이 있다는 데서 유래한다. 수많은 부산시민이 찾는 금정산은 높은 산세에다 동래온천장, 금강공원, 산",
    },
    {
        "id": "m-토함산",
        "name": "토함산",
        "region": "경북 경주시",
        "lat": 35.8017722,
        "lng": 129.3452135,
        "elevation_m": 746,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 4,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "토함산 — 경북 경주시 위치 명산.",
    },
    {
        "id": "m-내연산",
        "name": "내연산",
        "region": "경북 포항시",
        "lat": 36.111944,
        "lng": 129.369444,
        "elevation_m": 711,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "낙동정맥 줄기가 주왕산을 옆으로 지나쳐 내려오다가 동해안 쪽으로 뻗어가 솟은 산이 바로 내연산이다. 경상북도 포항시와 영덕군의 경계에 있는 내연산은 문수산(622m), 삼지봉(내연산 정상, 711.3m), 향로봉(932.4m), 우척",
    },
    {
        "id": "m-방태산",
        "name": "방태산",
        "region": "강원 인제군",
        "lat": 37.8882546,
        "lng": 128.3901797,
        "elevation_m": 1446,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관"],
        "description": "이땅에서 식물살이가 가장 좋은 산이다. 고랫재 같은 흙에 덮인 후덕한 육산의 싸리나무, 복자기, 소나무, 산벚나무, 만병초… 수종(樹種) 전시장처럼 다양한 나무들과 고사리, 관중, 우산나물, 곰취, 수리취, 얼레지, 연령초, 양지꽃,",
    },
    {
        "id": "m-점봉산",
        "name": "점봉산",
        "region": "강원 양양군",
        "lat": 38.04874,
        "lng": 128.425643,
        "elevation_m": 1426,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 1,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["단풍 명소", "설경 명소", "정상 전망 우수"],
        "description": "오색약수 품은 설악산 전망대> 점봉산은 오색온천과 약수를 끼고 있긴 하지만 설악의 그늘에 가려 그 위풍을 펴지 못했었다. 하지만 가을이면 가야동을 축소시켜 놓은 듯한 주전골과 설악의 천불동을 옮겨 놓은 듯한 기암들이 어울려 단풍산행지",
    },
    {
        "id": "m-대암산",
        "name": "대암산",
        "region": "강원 인제군",
        "lat": 38.2110649,
        "lng": 128.1347132,
        "elevation_m": 1313,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "고층습원으로 잘 알려진 대암산은 정상부근에 있는 분지형으로 된 큰 용늪과 작은 용늪이 있다. 이 습원의 크기는 동서 약 150미터, 남북 약 100미터 내외의 부정형으로 서북에서 동남으로 완만한 경사를 이루고 있다. 높은 학술적 가치",
    },
    {
        "id": "m-백덕산",
        "name": "백덕산",
        "region": "강원 영월군",
        "lat": 37.3964738,
        "lng": 128.2935238,
        "elevation_m": 1350,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소", "계곡 트레킹"],
        "description": "백덕산은 평창군 방림면과 평창읍, 영월군 주천면과 수주면, 횡성군 안흥면의 경계에 솟아있는 해발 1350.1m의 산이다. 천연 원시림을 간직한 주계곡과 함께 설경이 뛰어나 겨울철 산행지로 유명하다. 더욱이 백덕산 남서쪽 연화봉 아래에",
    },
    {
        "id": "m-청옥산",
        "name": "청옥산",
        "region": "강원 삼척시",
        "lat": 37.4346712,
        "lng": 128.9727262,
        "elevation_m": 1256,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-선자령",
        "name": "선자령",
        "region": "강원 평창군",
        "lat": 37.7125,
        "lng": 128.712778,
        "elevation_m": 1157,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-용화산",
        "name": "용화산",
        "region": "강원 춘천시",
        "lat": 37.901111,
        "lng": 127.831944,
        "elevation_m": 878,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소", "암릉 경관", "사찰 탐방"],
        "description": "용화산은 강원도 춘천시 사북면과 화천군 하남면 경계에 솟은 바위산이자 춘천의 의암댐, 소양댐, 춘천댐, 화천댐에 포위된 천혜의 성벽이다. 보통 들머리로 잡는 고성2리 양통골로 용화산에 들어서면 가장 먼저 바위봉우리들이 눈에 들어온다.",
    },
    {
        "id": "m-삼악산",
        "name": "삼악산",
        "region": "강원 춘천시",
        "lat": 37.888333,
        "lng": 127.820833,
        "elevation_m": 656,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관", "사찰 탐방"],
        "description": "삼악산은 등선봉, 청운봉에서 이어지는 한 봉우리다. 강촌의 대표적인 산으로 하나의 독립봉으로 사람들이 즐겨 찾고 있으며 접근이 용이하여 당일산행지로서 각광받고 있다. 거대한 성을 연상시키는 등선폭포 매표소를 지나 깎아지른 절벽 사이로",
    },
    {
        "id": "m-인왕산",
        "name": "인왕산",
        "region": "서울 종로구",
        "lat": 37.584722,
        "lng": 126.957778,
        "elevation_m": 340,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.72,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-아차산",
        "name": "아차산",
        "region": "서울 광진구",
        "lat": 37.5711235,
        "lng": 127.1043503,
        "elevation_m": 287,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.7,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "아차산 — 서울 광진구 위치 명산.",
    },
    {
        "id": "m-수락산",
        "name": "수락산",
        "region": "서울 노원구",
        "lat": 37.6992644,
        "lng": 127.0813401,
        "elevation_m": 641,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.38,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "수락산 — 서울 노원구 위치 명산.",
    },
    {
        "id": "m-불암산",
        "name": "불암산",
        "region": "서울 노원구",
        "lat": 37.663889,
        "lng": 127.095833,
        "elevation_m": 510,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.42,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "불암산 — 서울 노원구 위치 명산.",
    },
    {
        "id": "m-청계산",
        "name": "청계산",
        "region": "서울 서초구",
        "lat": 37.4275,
        "lng": 127.055,
        "elevation_m": 849,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.65,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-광교산",
        "name": "광교산",
        "region": "경기 수원시",
        "lat": 37.3449403,
        "lng": 127.0344434,
        "elevation_m": 582,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-달마산",
        "name": "달마산",
        "region": "전남 해남군",
        "lat": 34.3825578,
        "lng": 126.5852185,
        "elevation_m": 499,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "달마산 — 전남 해남군 위치 명산.",
    },
    {
        "id": "m-가리산",
        "name": "가리산",
        "region": "강원 홍천군",
        "lat": 37.8713832,
        "lng": 127.9564688,
        "elevation_m": 774,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-응봉산",
        "name": "응봉산",
        "region": "강원 삼척시",
        "lat": 37.235,
        "lng": 129.091111,
        "elevation_m": 1268,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "응봉산 — 강원 삼척시 위치 명산.",
    },
    {
        "id": "m-대야산",
        "name": "대야산",
        "region": "경북 문경시",
        "lat": 36.661111,
        "lng": 128.179722,
        "elevation_m": 931,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 1,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["계곡 트레킹"],
        "description": "백화산과 희양산을 지나 속리산 사이에 솟은 대야산은 속리산국립공원내에 포함되며, 백두대간 상의 산으로 경북과 충북 양쪽에 내외 선유동을 두고 있을 정도로 계곡이 특히 유명하다. 대야산 자락에서 흘러내린 물은 용추계곡을 형성, 문경 8",
    },
    {
        "id": "m-장안산",
        "name": "장안산",
        "region": "전북 장수군",
        "lat": 35.6291843,
        "lng": 127.5950744,
        "elevation_m": 1237,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관", "단풍 명소", "계곡 트레킹", "사찰 탐방"],
        "description": "장안산은 금남정맥과 호남정맥을 거느리며 백두대간의 기운을 충청도와 전라도에 전하는 호남의 종산이다. 여름에는 피서지, 가을에는 억새와 단풍으로 유명한데 이 일대의 계곡과 숲의 경관이 뛰어나 1986년 장수군 군립공원으로 지정되었다. ",
    },
    {
        "id": "m-천성산",
        "name": "천성산",
        "region": "경남 양산시",
        "lat": 35.4015733,
        "lng": 129.1062817,
        "elevation_m": 920,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "\"\"가파른 연봉들 첩첩이요 깊고 깊은 골짜기 굴 같다(連峰疊 洞府深邃)\"\"는 산이다. 웅상쪽에서 보면 깎아지른 듯한 산세가 단순·웅장한 홑산인데 양산쪽으로는 힘찬 산줄기를 여럿 뻗어내리면서 그 위에 수많은 암봉을 올려놓았다. 능선들 ",
    },
    {
        "id": "m-연화산",
        "name": "연화산",
        "region": "경남 고성군",
        "lat": 34.984444,
        "lng": 128.115556,
        "elevation_m": 1172,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "연화산 — 경남 고성군 위치 명산.",
    },
    {
        "id": "m-팔영산",
        "name": "팔영산",
        "region": "전남 고흥군",
        "lat": 34.637222,
        "lng": 127.415556,
        "elevation_m": 607,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 1,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "터질 듯한 봉만미를 자랑하는 산이다. '팔'자 들어간 산 치고 봉만미 뛰어나지 않은 것이 없지만 홍천이나 서산 팔봉산은 작아서 웅장함이 없는데 600미터의 높이에 여덟 암봉이 솟은 이 고흥 최고봉은 빼어난 위에 웅장하기까지 하다. 2",
    },
    {
        "id": "m-무학산",
        "name": "무학산",
        "region": "경남 창원시",
        "lat": 35.2101065,
        "lng": 128.535514,
        "elevation_m": 200,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-화왕산",
        "name": "화왕산",
        "region": "경남 창녕군",
        "lat": 35.5471482,
        "lng": 128.531694,
        "elevation_m": 758,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["억새 군락"],
        "description": "창녕읍의 진산으로 관룡산과 더불어 화왕산 군립공원을 이룬다. 화왕산 하면 억새를 떠올릴 만큼 억새의 대명사이기도 하다. ６만여평의 대평원에 십리 억새밭. 억새의 크기가 사람 키 높이를 훨씬 넘는다. 이것을 한 바퀴 도는 데 한 시간 ",
    },
    {
        "id": "m-가지산",
        "name": "가지산",
        "region": "경남 밀양시",
        "lat": 35.6202857,
        "lng": 129.0029231,
        "elevation_m": 1241,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "부산산악인들이 이름붙인 영남알프스는 낙동정맥 아랫부분의 천 미터 넘는 산들을 총칭하는 개념이다. 이 거울에 비친 下자 모양 산줄기는 그러나 고봉능선으로 이어진 탓에 낱낱으로는 썩 빼어난 것이 없다. 능선 안부와 정상의 고도차가 얼마 ",
    },
    {
        "id": "m-문복산",
        "name": "문복산",
        "region": "경북 청도군",
        "lat": 35.6760888,
        "lng": 129.0341305,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "문복산 — 경북 청도군 위치 명산.",
    },
    {
        "id": "m-영축산",
        "name": "영축산",
        "region": "경남 양산시",
        "lat": 35.5160152,
        "lng": 129.0527504,
        "elevation_m": 1081,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-고헌산",
        "name": "고헌산",
        "region": "경남 울주군",
        "lat": 35.6413942,
        "lng": 129.0846907,
        "elevation_m": 1033,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "고헌산 — 경남 울주군 위치 명산.",
    },
    {
        "id": "m-황석산",
        "name": "황석산",
        "region": "경남 함양군",
        "lat": 35.601,
        "lng": 127.762,
        "elevation_m": 1193,
        "difficulty": "hard",
        "walk_time_min": 200,
        "walk_time_max": 450,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["암릉 경관", "계곡 트레킹", "억새 군락"],
        "description": "황석산은 거창 남녘에 솟은 범상치 않은 바위산이다. 백두대간 줄기에서 뻗어 내린 네 개의 산 기백·금원·거망·황석 가운데 가장 끝 자락에 솟구친 이 봉우리는 덕유산에서도 선명하게 보인다．가을철에는 거망에서 황석으로 이어지는 능선에 광",
    },
    {
        "id": "m-삼성산",
        "name": "삼성산",
        "region": "경기 안양시",
        "lat": 37.409,
        "lng": 126.896,
        "elevation_m": 554,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-수리산",
        "name": "수리산",
        "region": "경기 안양시",
        "lat": 37.404,
        "lng": 126.902,
        "elevation_m": 489,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-검단산",
        "name": "검단산",
        "region": "경기 하남시",
        "lat": 37.51766,
        "lng": 127.24935,
        "elevation_m": 658,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "검단산 — 경기 하남시 위치 명산.",
    },
    {
        "id": "m-예봉산",
        "name": "예봉산",
        "region": "경기 남양주시",
        "lat": 37.558,
        "lng": 127.32,
        "elevation_m": 638,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-유명산",
        "name": "유명산",
        "region": "경기 가평군",
        "lat": 37.778,
        "lng": 127.59,
        "elevation_m": 864,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["계곡 트레킹"],
        "description": "대동여지도에 마유산으로 나오는 산인데 언제부턴가 유명산으로 불리게 되었다. 소문으로는, 산이름이 알려지지 않았을 때 이 산을 찾은 사람들이 일행 중 김유명이라는 여자 이름을 따서 붙였다고 한다. '입구에 있는 가지계곡'이라는 뜻의 입",
    },
    {
        "id": "m-축령산",
        "name": "축령산",
        "region": "경기 남양주시",
        "lat": 37.718,
        "lng": 127.316,
        "elevation_m": 622,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-주금산",
        "name": "주금산",
        "region": "경기 남양주시",
        "lat": 37.763,
        "lng": 127.476,
        "elevation_m": 814,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "주금산 — 경기 남양주시 위치 명산.",
    },
    {
        "id": "m-소요산",
        "name": "소요산",
        "region": "경기 동두천시",
        "lat": 37.938,
        "lng": 127.088,
        "elevation_m": 588,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관", "암릉 경관"],
        "description": "소요산은 영국 기준으로는 산 축에도 못 드는 언덕이다. 그들은 2000피트, 609.6미터부터 마운틴으로 보기 때문이다. 그렇지만 이 풍수지리의 땅 사람들은 50미터 높이의 독립봉조차도 혈맥이 흐르는 곳이라면서 산 대접을 해주었다. ",
    },
    {
        "id": "m-무갑산",
        "name": "무갑산",
        "region": "경기 광주시",
        "lat": 37.453,
        "lng": 127.481,
        "elevation_m": 578,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-운길산",
        "name": "운길산",
        "region": "경기 남양주시",
        "lat": 37.562,
        "lng": 127.345,
        "elevation_m": 610,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-천보산",
        "name": "천보산",
        "region": "경기 양주시",
        "lat": 37.85533,
        "lng": 127.11047,
        "elevation_m": 337,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-왕방산",
        "name": "왕방산",
        "region": "경기 포천시",
        "lat": 37.854,
        "lng": 127.134,
        "elevation_m": 737,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-박달산",
        "name": "박달산",
        "region": "경기 양평군",
        "lat": 37.28,
        "lng": 127.619,
        "elevation_m": 825,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "박달산 — 경기 양평군 위치 명산.",
    },
    {
        "id": "m-상원산",
        "name": "상원산",
        "region": "경기 양평군",
        "lat": 37.469,
        "lng": 127.674,
        "elevation_m": 1421,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-계방산",
        "name": "계방산",
        "region": "강원 홍천군",
        "lat": 37.728,
        "lng": 128.465,
        "elevation_m": 1579,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소", "정상 전망 우수"],
        "description": "백두대간의 오대산에서 곁가지를 쳐 남한강과 북한강을 가르는 지릉의 최고봉이다. 평창군의 유명한 가리왕산의 모산이기도 한 오대산 비로봉보다도 더 높아 백두대간을 바라보는 최고의 전망대를 제공하는 계방산은 한라, 지리, 설악, 덕유산에 ",
    },
    {
        "id": "m-노인봉",
        "name": "노인봉",
        "region": "강원 강릉시",
        "lat": 37.774,
        "lng": 128.832,
        "elevation_m": 1338,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-매봉산",
        "name": "매봉산",
        "region": "강원 태백시",
        "lat": 37.138,
        "lng": 128.973,
        "elevation_m": 755,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-금대봉",
        "name": "금대봉",
        "region": "강원 태백시",
        "lat": 37.199,
        "lng": 128.952,
        "elevation_m": 1418,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-가칠봉",
        "name": "가칠봉",
        "region": "강원 인제군",
        "lat": 38.228,
        "lng": 128.239,
        "elevation_m": 1242,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "가칠봉 — 강원 인제군 위치 명산.",
    },
    {
        "id": "m-용봉산",
        "name": "용봉산",
        "region": "충남 홍성군",
        "lat": 36.549,
        "lng": 126.682,
        "elevation_m": 381,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "용봉산 — 충남 홍성군 위치 명산.",
    },
    {
        "id": "m-덕숭산",
        "name": "덕숭산",
        "region": "충남 예산군",
        "lat": 36.691,
        "lng": 126.51,
        "elevation_m": 495,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "당나라 시인 유우석은 \"\"산이 높다고 다가 아니요 선풍(仙風)이 있어야 명산\"\"이라고 했다. 그래선지 덕숭산은 이웃의 큰 산 가야산(678.2m) 그늘임에도 수덕사라는 천년고찰의 본산이 되었다. 동쪽의 수암산(260.1m)부터 시작해",
    },
    {
        "id": "m-서산가야산",
        "name": "서산가야산",
        "region": "충남 서산시",
        "lat": 36.694,
        "lng": 126.547,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "서산가야산 — 충남 서산시 위치 명산.",
    },
    {
        "id": "m-도락산",
        "name": "도락산",
        "region": "충북 단양군",
        "lat": 36.905,
        "lng": 128.358,
        "elevation_m": 965,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "도락산(965.3m)은 월악산국립공원 끄트머리, 소백산국립공원과 이웃한 곳에 있다. '깨달음을 얻는 데는 나름대로 길이 있어야 하고 거기에는 또한 즐거움이 뒤따라야 한다'라는 뜻에서 우암 송시열이 산이름을 지었다고 전한다. 정상은 단",
    },
    {
        "id": "m-황학산",
        "name": "황학산",
        "region": "충북 제천시",
        "lat": 37.054,
        "lng": 128.239,
        "elevation_m": 912,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-금수산",
        "name": "금수산",
        "region": "충북 제천시",
        "lat": 37.039,
        "lng": 128.209,
        "elevation_m": 1016,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관", "단풍 명소", "설경 명소", "계곡 트레킹"],
        "description": "금수산(1015.8m)은 산세가 수려하고, 골이 깊고 기암절벽이 절경을 이뤄 사철 등산인들의 발길이 이어지는 곳이다. 비단폭을 깔아놓은 듯한 녹음 속에 계곡의 맑은 물소리, 물확에 떨어지는 폭포소리, 꽃, 녹음, 단풍, 설경 등 어느",
    },
    {
        "id": "m-제비봉",
        "name": "제비봉",
        "region": "충북 단양군",
        "lat": 36.96,
        "lng": 128.265,
        "elevation_m": 721,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-구병산",
        "name": "구병산",
        "region": "충북 보은군",
        "lat": 36.469,
        "lng": 127.803,
        "elevation_m": 876,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "구병산(876.3m)은 충북 보은군과 경북 상주시의 속리산국립공원 남쪽 국도 25호선 변에 자리잡고 있다. 속리산에서 뚝 떨어져나와 보은군 마로면 적암리와 경북과의 도계에 웅장하고 수려한 아홉 개 봉우리로 이루어진 산이라 '구봉산'으",
    },
    {
        "id": "m-희양산",
        "name": "희양산",
        "region": "충북 괴산군",
        "lat": 36.644,
        "lng": 127.929,
        "elevation_m": 996,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "희양산(999m)은 경북 문경시 가은읍과 충북 괴산군 연풍면의 경계를 이루며 백두대간에 우뚝 솟은 신령스런 암봉이다. 인근의 조령산(1026m)이나 백화산(1064m)보다 낮으나 빼어나기로 보자면 단연 으뜸이다. 희양산 봉암사 개산조",
    },
    {
        "id": "m-군자산",
        "name": "군자산",
        "region": "충북 괴산군",
        "lat": 36.787,
        "lng": 127.872,
        "elevation_m": 948,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-낙영산",
        "name": "낙영산",
        "region": "충북 괴산군",
        "lat": 36.62,
        "lng": 127.918,
        "elevation_m": 746,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-봉화청량산",
        "name": "봉화청량산",
        "region": "경북 봉화군",
        "lat": 36.928,
        "lng": 128.903,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "봉화청량산 — 경북 봉화군 위치 명산.",
    },
    {
        "id": "m-일월산",
        "name": "일월산",
        "region": "경북 영양군",
        "lat": 36.762,
        "lng": 129.247,
        "elevation_m": 1219,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-학가산",
        "name": "학가산",
        "region": "경북 안동시",
        "lat": 36.527,
        "lng": 128.623,
        "elevation_m": 870,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "학가산 — 경북 안동시 위치 명산.",
    },
    {
        "id": "m-문경황장산",
        "name": "문경황장산",
        "region": "경북 문경시",
        "lat": 36.815,
        "lng": 128.267,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "문경황장산 — 경북 문경시 위치 명산.",
    },
    {
        "id": "m-갑장산",
        "name": "갑장산",
        "region": "경북 상주시",
        "lat": 36.479,
        "lng": 128.098,
        "elevation_m": 806,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "갑장산 — 경북 상주시 위치 명산.",
    },
    {
        "id": "m-단석산",
        "name": "단석산",
        "region": "경북 경주시",
        "lat": 35.906,
        "lng": 129.176,
        "elevation_m": 827,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "단석산 — 경북 경주시 위치 명산.",
    },
    {
        "id": "m-팔봉산",
        "name": "팔봉산",
        "region": "경북 의성군",
        "lat": 36.382,
        "lng": 128.566,
        "elevation_m": 328,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["암릉 경관"],
        "description": "팔봉산은 산 같지도 않은, 300미터가 조금 넘는 동산이다. 그럼에도 같은 이름의 어떤 산보다 사람들이 많이 찾는, 유명한 산이다. 여덟 봉우리가 모두 바위로 되어있어 하늘금이 둥근 톱날처럼 역동적이고 스릴이 넘치기 때문이다. 그래 ",
    },
    {
        "id": "m-남덕유산",
        "name": "남덕유산",
        "region": "경남 함양군",
        "lat": 35.782,
        "lng": 127.683,
        "elevation_m": 1507,
        "difficulty": "hard",
        "walk_time_min": 270,
        "walk_time_max": 540,
        "trail_count": 0,
        "companion_fit": ["solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-웅석봉",
        "name": "웅석봉",
        "region": "경남 산청군",
        "lat": 35.352,
        "lng": 127.778,
        "elevation_m": 1099,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-삼봉산",
        "name": "삼봉산",
        "region": "경남 하동군",
        "lat": 35.247,
        "lng": 127.793,
        "elevation_m": 448,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-달음산",
        "name": "달음산",
        "region": "경남 양산시",
        "lat": 35.307,
        "lng": 129.211,
        "elevation_m": 587,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-광려산",
        "name": "광려산",
        "region": "경남 창원시",
        "lat": 35.36,
        "lng": 128.517,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "광려산 — 경남 창원시 위치 명산.",
    },
    {
        "id": "m-정병산",
        "name": "정병산",
        "region": "경남 창원시",
        "lat": 35.316,
        "lng": 128.602,
        "elevation_m": 567,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-방어산",
        "name": "방어산",
        "region": "경남 함안군",
        "lat": 35.315,
        "lng": 128.439,
        "elevation_m": 532,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "방어산 — 경남 함안군 위치 명산.",
    },
    {
        "id": "m-천황산",
        "name": "천황산",
        "region": "경남 밀양시",
        "lat": 35.434,
        "lng": 129.04,
        "elevation_m": 1189,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-미륵산",
        "name": "미륵산",
        "region": "경남 통영시",
        "lat": 34.847,
        "lng": 128.415,
        "elevation_m": 696,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-신어산",
        "name": "신어산",
        "region": "경남 김해시",
        "lat": 35.248,
        "lng": 128.717,
        "elevation_m": 460,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-불모산",
        "name": "불모산",
        "region": "경남 김해시",
        "lat": 35.252,
        "lng": 128.782,
        "elevation_m": 399,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-백운산",
        "name": "백운산",
        "region": "전남 광양시",
        "lat": 35.083,
        "lng": 127.622,
        "elevation_m": 1218,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "workout"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["암릉 경관"],
        "description": "&nbsp;웅석봉 줄기가 남으로 흐르다가 마근담봉에서 세갈래 줄기로 나뉘어진다. 감투봉 이방산을 지나 시천면 소재지 방향과 수양산,화장산방향 그리고 백운리와 운리를 경계지으며 흐르는 줄기 끝자락이 바로 백운산이다. 백운산은 그다지 높",
    },
    {
        "id": "m-모악산",
        "name": "모악산",
        "region": "전북 김제시",
        "lat": 35.728,
        "lng": 127.085,
        "elevation_m": 795,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "이름처럼 포근한 어머니산이다. 안으로 들어가보면 안다. 구성산(489.7m), 청도재, 상봉, 안덕봉(617m)을 잇는 마름모꼴 산릉이 물, 불, 바람 삼재(三災)를 막아주는 형세다. 이런 까닭에 강증산은 동학 난리 끝의 어수선한 상",
    },
    {
        "id": "m-방장산",
        "name": "방장산",
        "region": "전북 정읍시",
        "lat": 35.553,
        "lng": 126.857,
        "elevation_m": 734,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["암릉 경관", "정상 전망 우수"],
        "description": "호남고속국도를 타고 남으로 가다보면 호남평야가 끝나면서 길이 산으로 들어간다. 왼쪽에서는 입암산 정상의 농바위가 문인화처럼 인상적인데 오른쪽으로는 포장(布帳)처럼 장대한 산이 솟아있다. 방장산이다. 평지에서 불쑥 솟구친 데다 능선들이",
    },
    {
        "id": "m-입암산",
        "name": "입암산",
        "region": "전북 정읍시",
        "lat": 35.513,
        "lng": 126.962,
        "elevation_m": 626,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-강천산",
        "name": "강천산",
        "region": "전남 담양군",
        "lat": 35.402,
        "lng": 127.048,
        "elevation_m": 586,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["폭포 경관", "암릉 경관", "계곡 트레킹"],
        "description": "1981년 사상 최초로 군립공원이 된 산이다. '군립'이라는 규모에 걸맞게 600미터가 채 안되지만 '공원'답게 뛰어난 계류미를 자랑한다. 위는 육산, 아래는 골산(骨山)이어서 바위들이 거의 산중턱 아랫녘에 몰려있다. 하여 5킬로미터",
    },
    {
        "id": "m-추월산",
        "name": "추월산",
        "region": "전남 담양군",
        "lat": 35.178,
        "lng": 126.982,
        "elevation_m": 731,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["설경 명소", "사찰 탐방"],
        "description": "가을이면 산봉우리가 보름달에 맞닿을 정도로 높다고 해 이름지어진 추월산은 마치 충북의 월악산을 담양에 옮겨놓은 듯 기암절벽의 절경과 함게 절벽끝에 아슬아슬 매달린 듯한 보리암은 보는 것만으로도 가슴이 움츠러들게 만든다. 보리암의 창건",
    },
    {
        "id": "m-병풍산",
        "name": "병풍산",
        "region": "전남 담양군",
        "lat": 35.247,
        "lng": 126.988,
        "elevation_m": 796,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;병풍산(796m)은 화천군 간동면에 자리한 산으로 산꾼들의 발걸음이 거의 닿지 않은 오지의 산이다.철원군을 지나온 북한강의 원류와 양구군에서 흘러든 수입천과 서천의 물이 모여 거대한 호수를 이룬 파로호 주변에는 일산, 성주",
    },
    {
        "id": "m-봉황산",
        "name": "봉황산",
        "region": "전남 화순군",
        "lat": 35.064,
        "lng": 126.988,
        "elevation_m": 818,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "봉황산은 기존에 있던 희미한 등산로를 대대적으로 보수공사를 하여 등산객들이 불편함이 없도록 하였고, 금오산을 오르는 길이 잘 발달되어 있기 때문에 연계해서 등산하기 에 편리하도록 되어 있다. 죽포에서 정상을 거쳐 율림치 주차장에 이르",
    },
    {
        "id": "m-제암산",
        "name": "제암산",
        "region": "전남 보성군",
        "lat": 34.936,
        "lng": 127.009,
        "elevation_m": 807,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
    {
        "id": "m-금전산",
        "name": "금전산",
        "region": "전남 고흥군",
        "lat": 34.744,
        "lng": 127.092,
        "elevation_m": 668,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-백아산",
        "name": "백아산",
        "region": "전남 화순군",
        "lat": 35.232,
        "lng": 127.052,
        "elevation_m": 810,
        "difficulty": "medium",
        "walk_time_min": 150,
        "walk_time_max": 360,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "view"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&#160;",
    },
    {
        "id": "m-성산일출봉",
        "name": "성산일출봉",
        "region": "제주 서귀포시",
        "lat": 33.458,
        "lng": 126.942,
        "elevation_m": None,
        "difficulty": "easy",
        "walk_time_min": 60,
        "walk_time_max": 180,
        "trail_count": 0,
        "companion_fit": ["vulnerable", "family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "성산일출봉 — 제주 서귀포시 위치 명산.",
    },
    {
        "id": "m-산방산",
        "name": "산방산",
        "region": "제주 서귀포시",
        "lat": 33.24,
        "lng": 126.319,
        "elevation_m": 507,
        "difficulty": "medium",
        "walk_time_min": 90,
        "walk_time_max": 240,
        "trail_count": 0,
        "companion_fit": ["family", "solo"],
        "purpose_fit": ["balanced", "healing"],
        "crowding": 0.4,
        "national_park": False,
        "highlights": ["자연 경관 우수"],
        "description": "&nbsp;",
    },
]

MOUNTAIN_BY_ID = {m['id']: m for m in MOUNTAINS}
MOUNTAIN_BY_NAME = {m['name']: m for m in MOUNTAINS}
