# Generated by Django 5.2.4 on 2026-06-01 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_seed_sample_posts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('relation', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_emergencycontact',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HikingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(max_length=200)),
                ('hiked_date', models.DateField()),
                ('duration_min', models.PositiveIntegerField(default=0)),
                ('weather_summary', models.CharField(blank=True, max_length=100)),
                ('safety_label', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiking_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_hikingrecord',
                'ordering': ['-hiked_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200)),
                ('mountain', models.CharField(blank=True, max_length=100)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_favoritecourse',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course_id')},
            },
        ),
    ]
