# Generated by Django 6.0.1 on 2026-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_mountain_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterRiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=40, unique=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('risk_factor', models.CharField(blank=True, max_length=200)),
                ('evacuation_place', models.CharField(blank=True, max_length=200)),
                ('search_text', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'recommendations_disasterriskzone',
                'indexes': [models.Index(fields=['district'], name='recommendat_distric_da065b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MountainKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain_name', models.CharField(db_index=True, max_length=100)),
                ('height_m', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('selection_reason', models.TextField(blank=True)),
                ('source', models.CharField(max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendations_mountainknowledge',
                'indexes': [models.Index(fields=['mountain_name'], name='recommendat_mountai_ccc99b_idx')],
                'unique_together': {('mountain_name', 'source')},
            },
        ),
        migrations.CreateModel(
            name='TrailCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=60, unique=True)),
                ('mountain', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('elevation_gain_m', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('crowding', models.FloatField(default=0.4)),
                ('highlights', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'recommendations_trailcourse',
                'indexes': [models.Index(fields=['mountain'], name='recommendat_mountai_97f658_idx')],
            },
        ),
    ]
