# Generated by Django 6.0.1 on 2026-06-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_mountain_knowledge_trail_disaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountainknowledge',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mountainknowledge',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
