# Generated by Django 5.2.4 on 2026-06-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_mountain_knowledge_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountainTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tags', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendations_mountaintags',
            },
        ),
    ]
